/**
 * TradeSight AI - Gemini AI Vision Service
 * Sends chart screenshot + DOM metadata to Gemini 1.5/2.5 Flash/Pro with exponential backoff.
 */

import { TRADER_SYSTEM_PROMPT, buildVisionAnalysisPrompt, JSON_OUTPUT_SCHEMA } from '../prompts/trader-system-prompt.js';
import { cleanAndParseJsonResponse } from '../utils/validator.js';
import { Logger } from '../utils/logger.js';

export const AIService = {
  /**
   * Run technical chart vision analysis via Gemini API
   */
  async analyzeChart({ apiKey, model = 'gemini-2.5-flash', screenshotDataUrl, chartMeta = {} }) {
    if (!apiKey || !apiKey.trim()) {
      throw new Error('Gemini API Key is missing. Please configure your key in Settings.');
    }

    if (!screenshotDataUrl || !screenshotDataUrl.startsWith('data:image/')) {
      throw new Error('Invalid or missing chart screenshot. Ensure TradingView chart is visible.');
    }

    // Extract raw base64 string and MIME type
    const mimeMatch = screenshotDataUrl.match(/^data:(image\/[a-zA-Z+]+);base64,/);
    const mimeType = mimeMatch ? mimeMatch[1] : 'image/png';
    const base64Data = screenshotDataUrl.replace(/^data:image\/[a-zA-Z+]+;base64,/, '');

    const userPrompt = buildVisionAnalysisPrompt(chartMeta);

    const requestBody = {
      contents: [
        {
          role: 'user',
          parts: [
            {
              inlineData: {
                mimeType,
                data: base64Data
              }
            },
            {
              text: `${TRADER_SYSTEM_PROMPT}\n\n${userPrompt}\n\nREQUIRED RESPONSE FORMAT: Return valid JSON adhering strictly to this schema structure:\n${JSON.stringify(JSON_OUTPUT_SCHEMA, null, 2)}`
            }
          ]
        }
      ],
      generationConfig: {
        temperature: 0.15, // Low temperature for clinical, deterministic analysis
        topP: 0.85,
        maxOutputTokens: 2500,
        responseMimeType: 'application/json'
      }
    };

    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

    const rawResponse = await this._fetchWithRetry(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(requestBody)
    });

    const data = await rawResponse.json();

    if (data.error) {
      throw new Error(`Gemini API Error: ${data.error.message || 'Unknown error'}`);
    }

    const candidate = data.candidates?.[0];
    if (!candidate || !candidate.content?.parts?.[0]?.text) {
      throw new Error('No analysis generated by Gemini. The image might be obscured or blocked by safety filters.');
    }

    const generatedText = candidate.content.parts[0].text;
    Logger.debug('Raw AI Response received:', generatedText.slice(0, 200));

    // Validate and sanitize into strong typed object
    const validatedResult = cleanAndParseJsonResponse(generatedText);
    return validatedResult;
  },

  /**
   * Test API key connectivity
   */
  async testConnection(apiKey, model = 'gemini-2.5-flash') {
    if (!apiKey) throw new Error('API key is empty');

    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ role: 'user', parts: [{ text: 'Respond with: {"status": "ok"}' }] }],
        generationConfig: { responseMimeType: 'application/json' }
      })
    });

    const data = await response.json();
    if (data.error) {
      throw new Error(data.error.message || 'Verification failed');
    }
    return true;
  },

  /**
   * Internal fetch with exponential backoff on 429/503
   */
  async _fetchWithRetry(url, options, maxRetries = 3) {
    let delay = 1000;
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        const response = await fetch(url, options);

        // Success
        if (response.ok) {
          return response;
        }

        // Retryable status codes (429 Rate Limit, 503 Service Unavailable)
        if ((response.status === 429 || response.status === 503) && attempt < maxRetries) {
          Logger.warn(`HTTP ${response.status} encountered. Retrying in ${delay}ms... (Attempt ${attempt + 1}/${maxRetries})`);
          await new Promise((resolve) => setTimeout(resolve, delay));
          delay *= 2;
          continue;
        }

        // Non-retryable error
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error?.message || `API request failed with HTTP ${response.status}`);
      } catch (err) {
        if (attempt >= maxRetries) throw err;
        Logger.warn(`Fetch attempt ${attempt + 1} failed: ${err.message}. Retrying in ${delay}ms...`);
        await new Promise((resolve) => setTimeout(resolve, delay));
        delay *= 2;
      }
    }
  }
};
